### PR TITLE
Support symfony 3 components too

### PR DESCRIPTION
**Pull request by drAlberT**

### CODE REVIEW

**Comment by hkdobrev** [comment]
Hi @drAlberT! Thank you for this pull request! As you could see in Travis CI we test Spiderling on different versions of PHP and with different dependency versions including highest and lowest possible dependencies. Do you think you could address the failures in the builds? Let me know if you think they are not caused by the changed maximum allowed version.

**Comment by drAlberT** [comment]
Uhmm .. I digged a bit

> CHANGELOG
> =========
> 2.8.0
> -----
> 
>  * Added the `CssSelectorConverter` class as a non-static API for the component.
>  * Deprecated the `CssSelector` static API of the component.
> 

I think version 3.* is enforcing the deprecation and make old CssConverter no more available .. 

So .. this issue can't be satisfied in a such simple way .. sorry 

I think you can close it as invalid

**Comment by hkdobrev** [comment]
@drAlberT Perhaps we can detect the presence of this class. We could use the new API by default if available or try to fall back to the deprecated one if present. What do you think?

**Comment by drAlberT** [comment]
@hkdobrev Yes it would be a good idea to manage the migration to the new supported interface .. I agree with the approach you suggested `if class_exists .. else .. ` :)

**Comment by drAlberT** [comment]
@hkdobrev I'm going to close this PR, ok ?

**Comment by hkdobrev** [comment]
@drAlberT I thought you were going to implement the class exists check?

**Comment by drAlberT** [comment]
@hkdobrev LOL I thought to were too :) .. ok then will do, ASAP ;)

**Comment by hkdobrev** [comment]
I'm sorry for the misunderstanding. Unfortunately we won't have much time for that and we are not using it together with many Symfony components at the moment. But we'll happily accept contributions about wider support.

**Comment by hkdobrev** [comment]
Released as [`0.2.25`](https://github.com/OpenBuildings/spiderling/releases/tag/0.2.25). Thank you @drAlberT for the initial work on this and getting it started. There was a lot more involved with various version dependencies, deprecations and PHP version support, but was finally able to extend the Symfony version constraints.

**Comment by ZiZuu-store** [comment]
Great job!

**Comment by drAlberT** [comment]
Great!

**Pull request closed without merging**
